import "howl/styles/globals.css";
import { SessionProvider } from "next-auth/react";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "howl/trpc/react";
import NavBar from "./_components/nav/navBar";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "HowlX",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} font-main w-full font-thin`}>
      <body suppressHydrationWarning className="bg-bg text-text">
        <Toaster />
        <SessionProvider>
          <NavBar />
          <main className="">
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
