name: ci

on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      AUTH_MICROSOFT_ENTRA_ID_ID: ${{ secrets.AUTH_MICROSOFT_ENTRA_ID_ID }}
      AUTH_MICROSOFT_ENTRA_ID_SECRET: ${{ secrets.AUTH_MICROSOFT_ENTRA_ID_SECRET }}
      AUTH_MICROSOFT_ENTRA_ID_ISSUER: ${{ secrets.AUTH_MICROSOFT_ENTRA_ID_ISSUER }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint

    - name: Run build
      run: npm run build

    - name: Start Next.js app
      run: npm run start & npx wait-on http://localhost:3000

    - name: Run Cypress tests
      run: npx cypress run